package data;

/**
 * This class describes two keys of biometric data, generated by a biometric scanner.
 * This class is immutable.
 *
 * @author Daniel Berdie Pardo
 * @version 1.0 13 Jan 2018
 */
public class BiometricData {

    /**
     * The key corresponding to the face lecture.
     */
    private final long faceKey;

    /**
     * The key corresponding to the fingerprint lecture.
     */
    private final long fingerprintKey;

    /**
     * The constructor of the class.
     * @param faceKey The facial key.
     * @param fingerprintKey The fingerprint key.
     */
    public BiometricData(long faceKey, long fingerprintKey)
    {
        this.faceKey = faceKey;
        this.fingerprintKey = fingerprintKey;
    }

    public long getFaceKey() {
        return faceKey;
    }

    public long getFingerprintKey() {
        return fingerprintKey;
    }

    // region Overridden methods

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }

        if (other == null || getClass() != other.getClass()) {
            return false;
        }

        return faceKey == ((BiometricData)other).faceKey &&
                fingerprintKey == ((BiometricData)other).fingerprintKey;
    }

    @Override
    public String toString() {
        return "BiometricData{" + "facial key='" + faceKey + ", fingerprint key='" + fingerprintKey + '\'' + '}';
    }

    // endregion
}
